import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { HeroHeader } from "@/components/hero5-header";
import { ProgressiveBlur } from "@/components/motion-primitives/progressive-blur";
import Footer from "@/components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Web Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <HeroHeader/>
            {children}

            {/* <div className="pointer-events-none fixed bottom-0 left-0 w-full h-16 z-50">
  <div className="w-full h-full backdrop-blur-2xl [mask-image:linear-gradient(to_top,black,transparent)]"></div>
</div> */}

{/* <ProgressiveBlur
        className='w-full h-full backdrop-blur-2xl '
        blurIntensity={6}
      /> */}

          </ThemeProvider>
          <Footer/>
      </body>
    </html>
  );
}
